## **Variables problems**
##### *1.Create variables for your name, age, and city and print them?*

In [ ]:
name = "david"
age = 27
city = "chennai"

print(f"my name is {name}")
print(f"my age is {age}")
print(f"my city is {city}")

my name is david
my age is 27
my city is chennai

##### *2.Store two numbers in variables and print their sum?*

In [ ]:
a = 10
b = 30
print(f"sum:{a+b}")

sum:40


##### *3.Store length and width in variables and calculate the rectangle's area?*

In [ ]:
length = 11
width  = 12

print(f"Total rectangle area: {length*width} ")

Total rectangle area: 132


##### *4.Store your birth year and current year, then calculate your age?*

In [ ]:
Birth_year = 1999
current_year = 2026

print(f"My current age is : {current_year-Birth_year}")

My current age is : 27

##### *5.Store a product price and quantity, then calculate the total price?*

In [ ]:
Product_price = 99
quantity = 50

print(f"Total price :{Product_price*quantity}")

Total price :4950

##### *6.Store principal, rate, and time and calculate simple interest?*

In [ ]:
Principal = 200000
rate = 2
time = 1

print(f"simple interest: {Principal*rate*time/100} ")

simple interest: 4000.0

##### *7.Store Celsius temperature and convert it to Fahrenheit?*

In [ ]:
Celsius = 30
print(f"Fahrenheit:{Celsius*1.8+32} " )

Fahrenheit:86.0

##### *8.Store three subject marks and calculate the total and average?*

In [ ]:
Mathamatics = 100
Science = 99
English = 98

print(f"Total marks: {Mathamatics+Science+English}")
print(f"Average marks: {(Mathamatics + Science + English) /3}")

Total marks: 297
Average marks: 99.0

##### *9.Store a number and calculate its square and cube?*

In [ ]:
Number = 2
print(f"square: {Number**2}")
print(f"Cube: {Number**3}")

square: 4
Cube: 8

##### *10.Store salary and calculate yearly salary?*

In [ ]:
Salary = 22000
print(f"Yearly salary: {Salary*12}")

Yearly salary: 264000

##### *11.Store your age in a variable and print it?*

In [ ]:
Age = 27
print(f"My age is: {Age}")

My age is: 27

## **Float**
##### *12.Store the price of a product as a decimal number and print it?*

In [ ]:
Product_price = 99.00
print(f"Decimal price: {Product_price}")

Decimal price: 99.0

## **String**
##### *13.Store your name and print?*

In [ ]:
Name = "David"

print(f"my name is {Name}")

my name is David

## **Boolean**
##### *14.Create a variable called is_student and store True. Print it?*

In [ ]:
is_student  = True
print(is_student)

True

## **Integer + Integer**
##### *15.Store two numbers and print their sum?*

In [ ]:
A = 10
B = 20
print(f"Sum of Numbers: {A+B}")

Sum of Numbers: 30

## **Float + Float**
##### *16.Store two decimal numbers and calculate their total*

In [ ]:
D = 99.21
D1 = 77.90
print(f"decimal numbers total: {D+D1}")

decimal numbers total: 177.11

## **String**
##### *17.Store your first name and last name in two variables and print them together*

In [ ]:
First_name = "david"
Last_name = "Raj"
print(f"My full name is : {First_name+' '+Last_name}")

My full name is : david Raj

### **Find the data type**
##### *18.Create these variables and print their types using type()?*

In [ ]:
age = 25
salary = 22000.5
name = "David"
is_working = True

print(age,type(age))
print(salary,type(salary))
print(name,type(name))
print(is_working ,type(is_working ))

25 <class 'int'>
22000.5 <class 'float'>
David <class 'str'>
True <class 'bool'>

In [ ]:
a = 30
b = 40

b = a

print(b)

30

## **type()**
##### *19.Create these variables and print their types using type()?*

In [ ]:
a = 10
b = 20 
print(a,type(a))
print(b,type(b))

10 <class 'int'>
20 <class 'int'>

#### **Personal Details**
##### *20.Get name, age, and city Print them in one line using sep?*

In [ ]:
name = "david"
age = 27
city = "chennai"

print(name, age, city,sep="\n")


print(f"my name is {name}, and is {age} from {city}")

david
27
chennai
my name is david, and is 27 from chennai

## **Type Casting**
##### *21.Take two numbers using input(), Convert them to integers, Print their sum?*

In [ ]:
user_1 = int(input("Enter a Number1: "))
user_2 = int(input("Enter a Number1: "))

sum_number = user_1 + user_2
print(sum_number)

50

#### **Print Without New Line**
##### *22. New Line*
* Python
* is
* easy

In [ ]:
print("Python")
print("is")
print("esay")

Python
is
esay

##### *23.Simple Calculator*



* Take:

* number1
* number2

* Print:
Addition:
Subtraction:
Multiplication:
Division:
Floor Division:
Modulus:
Power**:

In [ ]:
number1 = int(input("Enter number 1: "))
number2 = int(input("Enter number 1: "))

print(number1+number2)
print(number1-number2)
print(number1*number2)
print(number1/number2)
print(number1//number2)
print(number1%number2)

60
-20
800
0.5
0
20

##### *24.Take length and width.*

Calculate:

*  Area
* Perimeter

In [ ]:
length = int(input("Enter a length: "))
width = int(input("Enter a width: "))

area = length * width
print(area)

perimeter = 2 * length + width
print(perimeter)

200
40

##### *25.Print:*

* Value: 50
* Type: <class 'int'>
* ID: ........

In [ ]:
x = 100
print("value: ", x)
print(type(x))
print(id(x))

value:  100
<class 'int'>
140715524681944

#### *26.del Challenge*
Create:
* name = "David"
* age = 26
* city = "Chennai"

In [ ]:
# name = "david"
# age  = 26
# city = "chennai"

# print("name:",name)
# print("age:",age)
# print("city: ",city)

del age
# print("age: ",age)

name: david
age: 26
city:  chennai

##### *27. ASCII*
8. Character → ASCII
* Input:

A

Output:

ASCII: 65

In [ ]:
print("Ascli: A")

Ascli: A

##### *28. ASCII → Character*

Input:

65

Output:

Character: A

In [ ]:
print("Character:",chr(65))

Character: A

#### *29. ASCII Difference*

Take two characters:

A
B

Output:

A = 65
B = 66
Difference = 1

In [ ]:
name = "david"
age = 27
mark1 = int(input("Enter Mark1: "))
mark2 = int(input("Enter Mark1: "))
mark3 = int(input("Enter Mark1: "))

Total = mark1 + mark2 + mark3
Average = Total/3
print("----------Student Details----------\n")
print("Name: ",name,end=" | ")
print("Age: ",age)
print(Total)
print(Average)
print(type(age))
print(type(Total))
print(id(Total))

----------Student Details----------

Name:  david | Age:  27
179
59.666666666666664
<class 'int'>
<class 'int'>
140715524684472

In [ ]:
# print("David", 27, "Chennai", sep=" , ")

# print("Hello",end=" - ")
# print("World")

# print("A", "B", "C" , sep="-", end="!")

A-B-C!

### **arithmetic operators**

##### *30. Two Number Operations*
Take two numbers and find:

* Sum
* Difference
* Product
* Quotient

In [ ]:
num1 = int(input("Enter Num1: "))
num2 = int(input("Enter Num2: "))

total = num1 + num2
difference = num2 - num1
product = num1 * num2
quotient = num1 / num2

print("Sum:", total)
print("Difference:", difference)
print("Product:", product)
print("Quotient:", quotient)

Sum: 40
Difference: 0
Product: 400
Quotient: 1.0

##### *31.Take the side of a square. Find:*

* Area
* Perimeter

In [ ]:
square = 20
width = 50

area = square * width
perimeter = 4*(square + width)
print(area)
print(square)

1000
20

##### *32. Shopping Bill*

Take:

Product price = ₹250
Quantity = 4

Find the total bill.

In [ ]:
Product_price = 250
quantity = 4

total_bill = Product_price*quantity
print(total_bill)

1000

##### *33. Calculate the discount amount and final price.*

Take:

* Price
* Discount percentage

Calculate the discount amount and final price.

In [ ]:
price = 100
discount = 10

Discount_price  = price*discount/100
final_price = price-Discount_price
print(final_price)

90.0

##### **Salary**

##### *34.Take:Basic salary Allowance Deduction*

In [ ]:
basic_salary = 22000
allowance = 2000
deduction = 2000

net_salary = basic_salary+allowance
print("Take Home Salary: ",net_salary)

Take Home Salary:  24000

In [ ]:
name = "david"
age = 27
course = "GenAi"

print(f"my name is {name},I am {age} years old, and curenntly pursuing a {course} course at Techpanda Academy.")

my name is david,I am 27 years old, and curenntly pursuing a GenAi course at Techpanda Academy.

##### *35.Get student name, age and course using input(). Convert age to int and display the details using print()?*

In [ ]:

student_name = input("Enter Student name: ")
student_age = int(input("Enter Student Age: "))
course = input("Enter Course: ")

print(f"Student Name: {student_name}")
print(f"Student Age: {student_age}")
print(f"Course: {course}")

Student Name: David
Student Age: 27
Course: GenAi

### **Arithimatic Operators**** 
##### *36.Get two numbers from the user and display addition, subtraction, multiplication, division, floor division and modulus*

In [ ]:
num1 = int(input("Enter Num1: "))
num2 = int(input("Enter Num2: "))

addition = num1 + num2
subtraction = num1 - num2
multiplication =  num1 * num2
division = num1 / num2
floor_division =  num1 // num2
modulus =  num1 % num2
 
print("Addition:",addition)
print("Subtraction:",subtraction)
print("Multiplication:",multiplication)
print("Division:",division)
print("Floor_division:",floor_division)
print("Modulus:",modulus)

Addition: 87
Subtraction: -47
Multiplication: 1340
Division: 0.29850746268656714
Floor_division: 0
Modulus: 20

### **Comparison Operators**


#### *36.Take two numbers from the user and print which number is greater*

In [ ]:
num1 = int(input("Enter Num1: "))
num2 = int(input("Enter Num2: "))

if num1>=num2:
    print("Greater Num: ",num1)
else:
    print("greater Num",num2)

greater Num 20

#### *37.Take a student's marks and check whether the student scored 50 or more*

In [ ]:
student_marks = int(input("Student marks: "))

if student_marks>=50:
    print("pass")
else:
    print("fail")

pass

##### *38.Take a person's age and check whether they are between 18 and 60*

In [ ]:
person_age = int(input("Enter age: "))

if person_age>=18 and person_age<=60:
    print("Eligable")
else:
    print("not Eligable")

not Eligable

### **Logical Operators**

##### *39.Take username and password from the user. Allow login only when BOTH are correct*

In [ ]:
user_name = input("Enter user name: ")
user_password = input("Enter user password: ")

if user_name == "david" and user_password == "1234":
    print("Login sucessfully")
else:
    print("login failed")

login failed

Task 5

Take age and salary from the user.

A person is eligible for a loan only if:

Age is 21 or above
Salary is ₹25,000 or above

Use the and operator.

In [ ]:
age = int(input("Enter age: "))
salary = int(input("Enter salary: "))

if age>=21 and salary>=25000:
    print("eligible for loan")
else:
    print("not eligible for loan")

eligible for loan

Task 6:
Take a number. Check whether it is:

greater than 10 and
less than 100

In [ ]:
num = int(input("Enter Number"))

if num>10 and num<00:
    print("Number is between 10 and 100",num)
else:
    print("Number is not between 10 and 100",num)

Number is between 10 and 100 33

### **Lists**
##### *40.Create a list of 5 expenses. Calculate the total expense*

In [ ]:
expenses = [10,200,400,240,1200]
total = sum(expenses)
print(total)

2050

Task 8:
Create a list of 5 numbers. Find the largest and smallest number.

In [ ]:
Largest_num = [12,40,608,240,506]

Larger_number = min(Largest_num)
print(Larger_number)

12

#### *41.Create a list of employee names. Ask the user for a name and check whether the employee exists*

In [ ]:
employee_names = ["yesu","sam","david","mahi"]

user_name = input("Enter name: ")

if user_name in employee_names:
    print("name already exist",user_name)
else:
    print("new name",user_name)

name already exist yesu


##### *42.You have:Python Java Python SQL Java Create a collection that stores only unique skills.*

In [ ]:
unqiue_skils = {"Python","java","Python","SOL","java"}
print(unqiue_skils)

{'Python', 'java', 'SOL'}

##### *43.Create two sets of employee departments and find the departments common to both*

In [ ]:
allowed_location = {"chennai","tambram","villupuram"}
user_location = input("Enter location: ")

if user_location in allowed_location:
    print("Allowed loaction",user_location)
else:
    print("not allowed",user_location)

Allowed loaction chennai

### **Dictionaries**

##### *44.Create a dictionary containing an employee's*

name
age
department
salary

In [ ]:
mydict = {
    "name": "david",
     "age":27,
     "department":"genai  developer",
     "salary":100000
}
print(mydict["name"])

david

##### *45.Create a product dictionary with product names and prices. Ask the user for a product and display its price*

In [ ]:
products = {
    "laptop": 50000,
    "phone": 25000,
    "headphones": 3000,
    "keyboard": 1500
}

product_enter = input("Enter product: ")
print(products[product_enter])

25000

#####  *46.Create a dictionary containing 5 employees and their salaries. Find the employee with the highest salary*

In [ ]:
employees = {
    "David": 50000,
    "Raj": 75000,
    "Kumar": 60000,
    "Arun": 45000,
    "Vijay": 90000
}

Highest_salary = max(employees.values())
print(Highest_salary)

90000

##### *47.Reverse a list*

numbers = [1, 2, 3, 4, 5]

Reverse it without using reverse() or slicing [::-1].

In [ ]:
numbers = [1, 2, 3, 4, 5]

reverse = []

for num in numbers:
    reverse.insert(0,num)
print(reverse)

[5, 4, 3, 2, 1]

##### *48.Count positive numbers*
numbers = [-5, 10, -2, 7, 0, 15, -8]

Count how many positive numbers are present.

In [ ]:
numbers = [-5, 10, -2, 7, 0, 15, -8]

positive = 0

for num in numbers:
    if num>0:
        positive = positive+1

print(positive)

3

##### *49.Count negative numbers*
numbers = [10, -5, 8, -2, -7, 20]

In [ ]:
numbers = [10, -5, 8, -2, -7, 20]

negative = 0

for num in numbers:
    if num<0:
        negative += 1
print(negative)

3

##### *50.Count odd numbers*
* numbers = [11, 20, 33, 42, 55, 60, 71]

In [ ]:

numbers = [11, 20, 33, 42, 55, 60, 71]

odd = 0

for num in numbers:
    if num%2==1:
        odd +=1
print(odd)

4

##### *51.Calculate average without sum()*
* numbers = [10, 20, 30, 40, 50]

In [ ]:
numbers = [10, 20, 30, 40, 50]

total = 0

for num in numbers:
    total = total + num
average = total/5
print(average)

30.0

##### *52.Find the smallest number without min()*
* numbers = [45, 12, 78, 3, 90, 21]

In [ ]:
numbers = [45, 12, 78, 3, 90, 21]

smallest = numbers[0]

for num in numbers:
    if num<smallest:
        smallest = num
print(smallest)

3

##### *53.Count numbers greater than 50*
* numbers = [20, 65, 12, 90, 45, 72, 30]

In [ ]:
numbers = [20, 65, 12, 90, 45, 72, 30]

greater =  0

for num in  numbers:
    if num>=50:
        greater=greater+1
print(greater)

3

##### *54.Separate even and odd numbers*
* numbers = [1, 2, 3, 4, 5, 6]

In [ ]:

numbers = [1, 2, 3, 4, 5, 6]

even = []
odd = []

for num in numbers:
    if num%2==0:
        even = even  + [num]
    elif num%2==1:
        odd = odd + [num]
print(even)
print(odd)

[2, 4, 6]
[1, 3, 5]

##### *56.Calculate total marks*

In [ ]:
marks = {
    "Python": 80,
    "SQL": 70,
    "HTML": 85,
    "CSS": 75
}

total = 0

for mark in marks.values():
    total = total + mark
print(total)

310

##### *57.Find the highest mark*

In [ ]:
marks = {
    "Python": 80,
    "SQL": 70,
    "HTML": 95,
    "CSS": 75
}

highest = 0
highest_subject = 0

for subject, mark in marks.items():
    if mark>highest:
        highest = mark
        highest_subject =  subject

print(highest_subject,highest)

HTML 95

##### *58.Count students who passed*

A student passes if their mark is 50 or above.

In [ ]:
students = {
    "David": 85,
    "John": 45,
    "Sam": 72,
    "Ravi": 38,
    "Alex": 65
}


Pass = 0

for student in students.values():
    if student>50:
        Pass = Pass +1
print(Pass)

3

##### *59.Print all elements*

In [ ]:
numbers = {10, 20, 30, 40, 50}

for num  in numbers:
    print(num)

50
20
40
10
30

##### *60.Count unique numbers*

In [ ]:
numbers = {10, 20, 10, 30, 20, 40, 10}

unique = 0

for num in numbers:
        unique  += 1
print(unique)

4

##### *61.Find common elements*

In [ ]:
set1 = {10, 20, 30, 40}
set2 = {30, 40, 50, 60}

common = set()

for num in set1:
    if num in set2:
        common.add(num)
print(common)

{40, 30}

#### *62.Find the total*

In [ ]:
numbers = [10, 20, 30, 40, 50]

total = 0

for num in numbers:
      total+=num
print(total)

150

##### *63.Find the Largest Number*

In [ ]:
numbers = [25, 10, 45, 7, 90, 32]

largest  =  numbers[0]

for num in numbers:
    if num>largest:
        largest = num
print(largest)

90

##### *64Find the smallest number in the tuple without using min().*

In [ ]:
numbers = (15, 25, 10, 40, 30)

smallest = numbers[0]

for num in numbers:
    if num<smallest:
        smallest = num
print(smallest)

10

### **while loop< lesser than**

##### *65.If a number is less than 10, print:*

In [ ]:
num = int(input("Enter a number: "))

if num<10:
    print(num,"Number is less than 10")

2 Number is less than 10

##### *66.If a number is less than 0, print:*

In [ ]:
num = int(input("Enter a number: "))

if num<0:
    print(num,"Negative Number")

##### *67.Print numbers from 1 to 5 using while and <.*

In [ ]:
num = 1

while num<=5:
    print(num)
    num += 1

1
2
3
4
5

##### *68.Print numbers from 1 to 10 using while and <.*

In [ ]:
num = 1

while num<=10:
    print(num)
    num += 1

1
2
3
4
5
6
7
8
9
10

##### *69.Start from 0 and print numbers until 4.*

In [ ]:
num = 0

while num<=4:
    print(num)
    num += 1

0
1
2
3
4

### **Countdown Game**
##### *70.Start with 0. Keep increasing the number while it is less than 5.*

In [ ]:
num = 0

while num<5:
    print(num)
    num += 1

0
1
2
3
4

### **Secret Number Game**
##### *71.The secret number is 10.Keep asking the user to enter a number while the entered number is less than 10.*

In [ ]:
secret_number = 10
guess = int(input("Guess the secret number: "))

while guess!= secret_number:

    if guess<10:
        print("too small")

    guess = int(input("Guess the secret number: "))
    
print("correct")

too small
too small
too small
too small
too small
too small
correct

### **⭐python loop pattern programming**
####  *72.Print the below Pattern:* 

\*\*\*\*\*    
\*\*\*\*\*   
\*\*\*\*\*    
\*\*\*\*\*  
\*\*\*\*\*    

*72.Print the below Pattern:*

In [ ]:
row = int(input("Enter a Row:"))
column = int(input("Enter a column:"))

a = 1

while a<=row: ## row
    b = 1
    while b<=column: ## column
        print("*",end="")
        b += 1
    
    a += 1
    print()

******
******
******
******
******

### **⭐python loop pattern programming**
####  *73.Print the below Pattern:* 


```text
*
**
***
****
*****
```
 *73.Print the below Pattern:*

In [ ]:
row = int(input("Enter a Row:"))

i = 1

while i<=row:
    j=1
    while j<=i:
        print("*",end="")
        j += 1

    i += 1
    print()

*
**
***
****
*****

####  *74.Print the below Pattern:* 

```text
*****
****
***
**
*
```

*74.Print the below Pattern:*

In [ ]:
column = int(input("Enter a column:"))



while column>=1:
    j=1
    while j<=column:
        print("*",end="")
        j += 1

    column -= 1
    print()

*******
******
*****
****
***
**
*

####  *75.Print the below Pattern:* 

```text
1
12
123
1234
12345
```

In [ ]:
row = int(input("Enter a Row:"))


i = 1

while i<=row:
    j=1
    while j<=i:
        print(j,end="")
        j += 1

    i += 1
    print()

1
12
123
1234
12345

####  *76.Print the below Pattern:* 

```text
1
22
333
4444
55555
```
####  *76.Print the below Pattern:*

In [ ]:
row = int(input("Enter a Row:"))

i = 1

while i<=row:
    j=1
    while j<=i:
        print(i,end="")
        j += 1

    i += 1
    print()

1
22
333
4444
55555
666666
7777777

####  *78.Print the below Pattern:* 

```text
    *
   **
  ***
 ****
*****
```
####  *78.Print the below Pattern:*

In [ ]:
####  *78.Print the below Pattern:* 
a = int(input("Enter number of rows: "))


i = 1

while i<=a:
    j = 1

    # print spaces
    while j<= a-i:
        print(" ",end="")
        j += 1 

    # print stars
    k = 1
    while k<=i:
      print("*",end="")
      k += 1 


    i += 1
    print()

        *
       **
      ***
     ****
    *****
   ******
  *******
 ********
*********

####  *78.Print the below Pattern:* 

```text
*
**
***
****
*****
****
***
**
*
```

In [ ]:
num = int(input("Enter number of rows: "))

i = 1

# Increasing 
while i <= num:
    j = 1

    while j <= i:
        print("*", end="")
        j += 1

    i += 1
    print()

# Decreasing 
i = num - 1

while i >= 1:
    j = 1

    while j <= i:
        print("*", end="")
        j += 1

    i -= 1
    print()

*
**
***
****
*****
****
***
**
*

####  *79.Print the below Pattern:* 

```text
1
12
123
1234
12345
```

In [ ]:
rows = int(input("Enter the row value: "))

for i in range(1,rows+1):
    for  j in range(1,i+1):
        print("*",end="")
          
    print()

*
**
***
****
*****

#### *80.Print numbers 1 to 10*

In [ ]:
for i in range(1,10+1):
    print(i)

1
2
3
4
5
6
7
8
9
10

#### *81.Print numbers 1 to 20*

In [ ]:
for i in range(1,20+1):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

#### *82.Print your name 5 times*

In [ ]:
names ="david"

for i in range(5):
    print(names)

david
david
david
david
david

#### *83.Find the sum of numbers from 1 to 100*

In [ ]:
sum = 0
for i in range(1,100+1):
    sum += i
print(sum)

5050

#### *84.Multiplication Table*

In [ ]:
tables = int(input("Enter a number:"))

for i in range(1,tables+1):
    print(f"{i}*{tables}=",i*tables)

1*5= 5
2*5= 10
3*5= 15
4*5= 20
5*5= 25

#### *85.Multiplication Table*

In [ ]:
for i in range(5):
    for j in range(i+1):
        j += 1
        print("*",end="")

    print()

*
**
***
****
*****

#### *86.Reverse Pattern*

In [7]:
num =  5

for i in range(num):
    for j in range(num):
        print("*",end="")

    num -= 1
    print()

*****
****
***
**
*

#### *86.Count vowels in a word*

In [17]:
names = input("Enter your name:")

vowels = 0

for name in names:
   if name in "aeiou":
      vowels += 1
print(vowels)

2

#### *86.Find the largest number*

In [21]:
numbers = [10, 45, 23, 99, 67]

largest = numbers[0]

for num in numbers:
    if num>largest:
        largest = num
print(largest)

99

#### *86.Mini Challenge*

Find:

* Sum
* Average
* Largest number
* Smallest number

In [35]:
numbers = [10, 20, 30, 40, 50]

length = len(numbers)
print(length)



total =  0
largest = numbers[0]
smallest = numbers[0]
for num  in numbers:
    total += num

    if num>largest:
        largest = num

    if num<smallest:
        smallest = num
average = total/len(numbers)

print(total)
print(average)
print(largest)
print(smallest)

5
150
30.0
50
10

#### *87.calacute the total number using function*

In [ ]:
def add(*numbers):
    total = 0

    for num in numbers:
        total+=num   

    return total

ans = add(12,39,40,79)
print(ans)

170
<class 'int'>

#### *88.Write a regex that validates a username.*

In [14]:
import re

text = "David123"

pattern = r"^[A-Za-z]+[0-9]+$"

result = re.search(pattern, text)

print(result)

<re.Match object; span=(0, 8), match='David123'>

#### *89.Write a regex that validates a 10-digit Indian phone number..*

In [26]:
import re

text = "+91 9876543210"

pattern = r"^\+91\s[6-9]\d{9}$"

result = re.search(pattern, text)

print(result)

<re.Match object; span=(0, 14), match='+91 9876543210'>

#### *90.Write a regex for a basic email address.*

In [31]:
import re

text = "david.raj@gmail.com"

pattern = r"^[a-z]+[.][a-z]+@gmail[.]com$"
result = re.search(pattern,text)

print(result)

<re.Match object; span=(0, 19), match='david.raj@gmail.com'>

#### *91.Write a regex to validate a password.*

In [33]:
import re

text = "David1234"

pattern = r"^[A-Za-z]+[0-9]+$"

result = re.search(pattern, text)

print(result)

<re.Match object; span=(0, 9), match='David1234'>

#### *92.Create an ATM withdrawal program.*

In [6]:

try:

    Account_balance = int(input("Enter an amount for Account balance: "))
    withdrawal_amount = int(input("Enter an amount to withdraw: "))

    if withdrawal_amount > Account_balance:
        raise ValueError("Insufficient balance")

    Remaining_balance = Account_balance - withdrawal_amount

    print(f"Withdrawal amount: {withdrawal_amount}")
    print(f"Remaining balance: {Remaining_balance}")

except ValueError as e:
    print(e)

Withdrawal amount: 46
Remaining balance: 31

#### *92.Student Marks.*

In [13]:
try:

    marks = int(input("Enter your Marks"))

    if marks<0 or  marks > 100:
        raise ValueError ("Please enter a mark between 0 to 100")
    print(f"you marks is {marks}")

    if marks >= 90:
        grade  = "A"
    elif marks >=75:
        grade = "B"
    elif marks >=50:
        grade = "c"
    else:
        grade = "d"

    print(f"Your grade is {grade}")

except ValueError as e:
    print(e)

you marks is 55
Your grade is c

#### *93.Age Verification.*

In [17]:
try:
    age =  int(input("Enter Your age:"))

    if age < 0:
        raise ValueError("Please enter a positive age")

    elif age > 120:
        raise ValueError("Please enter an age below 120")

    elif age < 18:
        raise ValueError("Access denied: You must be 18 or older")

    else:
        print("Access is allowed")

except ValueError as e:
        print(e)

Access denied: You must be 18 or older

#### *94.Calculator*

In [1]:
while True:

    try:
        num1 = int(input("Enter first number: "))
        operator = input("Enter operator (+ - * /): ")
        num2 = int(input("Enter second number: "))

        if operator not in ["+", "-", "*", "/"]:
            raise ValueError("Please enter a valid operator")

        if operator == "/" and num2 == 0:
            raise ZeroDivisionError("Cannot divide by zero")

        if operator == "+":
            result = num1 + num2
        elif operator == "-":
            result = num1 - num2
        elif operator == "*":
            result = num1 * num2
        elif operator == "/":
            result = num1 / num2

        print(f"Result: {result}")
        break

    except ValueError as e:
        print(e)

    except ZeroDivisionError as e:
        print(e)

Result: 64

#### *94.Create student.txt and write:*

In [5]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\student.txt","w") as myfile:

    mydata = myfile.write(
        "name: David\n"
        "Age: 27\n"
        "Course: Genai"
    )

    print(mydata)

33

#### *95.Read student.txt and print the complete content.*

In [6]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\student.txt", "r") as myfile:

    mydata = myfile.read()
    print(mydata)

name: David
Age: 27
Course: Genai

#### *96.Read student.txt one line at a time.*

In [7]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\student.txt", "r") as myfile:

    mydata = myfile.readline()
    print(mydata)

name: David

#### *97.Read all lines and store them in a list.*

In [8]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\student.txt", "r") as myfile:

    mydata = myfile.readlines()
    print(mydata)

['name: David\n', 'Age: 27\n', 'Course: Genai']

#### *98.Add this to student.txt without deleting the existing content:*

In [11]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\student.txt", "a") as myfile:

    mydata = myfile.write(
        "skill: python\n"
        "skill: machine learning\n"
    )
    print(mydata)

38

#### *99.Create skills.txt with:*

In [12]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\skill.txt", "x") as myskill:
    skillset = myskill.writelines(
        "Python\n"
        "Machine Learning\n"
        "Generative AI\n"
        "RAG\n"
    )

#### *100.Add this to student.txt without deleting the existing content:*

In [ ]:
with open("C:\\Users\\Yesu\\OneDrive\\Documents\\Desktop\\skill.txt", "x") as myskill:
    skillset = myskill.writelines(
        "Python\n"
        "Machine Learning\n"
        "Generative AI\n"
        "RAG\n"
    )

#### *101.Student Management*

In [2]:
class student:

    def __init__(self,name,age,course):### Constructor – Function is Temporary
        print("Student data")
        self.a =  name
        self.b = age
        self.c = course



Venkat = student("venkat",27,"genai")
print(f"name:{Venkat.a}")
print(f"age:{Venkat.b}")
print(f"course:{Venkat.c}")

print("-----------------")

baby = student("baby",27,"genai")

print(f"name:{baby.a}")
print(f"age:{baby.b}")
print(f"course:{baby.c}")

Student data
name:venkat
age:27
course:genai
-----------------
Student data
name:baby
age:27
course:genai

#### *102.Bank Account Management*

In [24]:
class Bankaccount:

    def __init__(self,account_holder,account_number,balance):
 
        self.a = account_holder
        self.b = account_number
        self.c = balance

    def display_account(self):
         print(f"account_holder: {self.a}")

    def deposit(self,amount):
        self.c += amount
        print(f"deposit amount:{self.c}")

    def withdraw(self,amount):
        self.c -= amount
        print(f"withdraw amount:{self.c}")

    

david = Bankaccount("David chinnappa Raj",292388399494,20000)
david.display_account()
david.deposit(5000)
david.withdraw(5000)

print("------------------------")

venkat = Bankaccount("venkat kumar",292388399554,40000)
venkat.display_account()
venkat.deposit(5000)
venkat.withdraw(5000)

account_holder: David chinnappa Raj
deposit amount:25000
withdraw amount:20000
------------------------
account_holder: venkat kumar
deposit amount:45000
withdraw amount:40000

#### *103.Employee Salary Management*

In [31]:
class Employee:

    def __init__(self,name,employee_id,department,salary):
        self.a  = name
        self.b = employee_id
        self.c = department
        self.d = salary

    def display_info(self):
        print(f"Employee name: {self.a}")
        print(f"employee_id: {self.b}")
        print(f"department: {self.c}")
        print(f"salary: {self.d}")

    def increase_salary(self,amount):
        self.d += amount
        print(f"the Salary increase:{self.d}")



david = Employee("David",144,"GenAI",60000)
david.display_info()
david.increase_salary(5000)

Employee name: David
employee_id: 144
department: GenAI
salary: 60000
the Salary increase:65000

#### *103.Constructor Challenge*

In [33]:
class Laptop:

    def __init__(self,brand,model,ram,price):
        self.a  = brand
        self.b = model
        self.c = ram
        self.d = price

    def display_info(self):
        print(f"Employee name: {self.a}")
        print(f"employee_id: {self.b}")
        print(f"department: {self.c}")
        print(f"salary: {self.d}")

    def upgrade_ram(self,new_ram):
        self.c = new_ram
        print(f"the Salary increase:{self.c}")



david = Laptop("Dell","spiron 15","16 GB", 55000)
david.display_info()
david.upgrade_ram("17 GB")

Employee name: Dell
employee_id: spiron 15
department: 16 GB
salary: 55000
the Salary increase:17 GB

#### *104.Inheritance Challenge*

In [36]:
class  Person:
    name = "david"
    age = 27

class Employee(Person):
    employee_id = 144
    salary = 60000

details  = Employee()
print(f"Name:{details.name}")
print(f"Age:{details.age}")
print(f"employee_id:{details.employee_id}")
print(f"salary:{details.salary}")

Name:david
Age:27
employee_id:144
salary:60000

#### *104.Polymorphism Challenge*

In [43]:
class Developer:
    def work(self):
        print("Developer → Writes Python code")
class Tester:
    def work(self):
        print("Tester → Tests software")
class Designer:
    def work(self):
        print("Designer → Creates UI designs")

obj1 = Developer()
obj2 = Tester()
obj3 = Designer()

obj1.work()
obj2.work()
obj3.work()

Developer → Writes Python code
Tester → Tests software
Designer → Creates UI designs

#### *105.Encapsulation Challenge*

In [51]:
class Bankaccount:

    def __init__(self, account_holder, account_number, balance):
        self.a = account_holder
        self.b = account_number
        self.__c = balance

    def display_account(self):
        print(f"Account holder: {self.a}")
        print(f"Account number: {self.b}")

    def deposit(self, amount):
        self.__c += amount
        print(f"Deposit amount: {amount}")

    def withdraw(self, amount):
        self.__c -= amount
        print(f"Withdraw amount: {amount}")

    def get_balance(self):
        print(f"Current balance: {self.__c}")


david = Bankaccount("David Chinnappa Raj", 292388399494, 20000)

david.display_account()
david.deposit(5000)
david.withdraw(2000)
david.get_balance()

Account holder: David Chinnappa Raj
Account number: 292388399494
Deposit amount: 5000
Withdraw amount: 2000
Current balance: 23000

#### *106.Function as a parameter*

In [ ]:
def send_email():
    print("sending email")
def send_sms():
    print("sending sms")
def notification(func): ## func as paramter
    func()

notification(send_email)

sending email

#### *107.Nested function*

In [16]:
def user_system():
    print("User system started")

    def login():
        print("Login successful")
      
    return login

ans = user_system()
print(ans())

User system started
Login successful
None

#### *108.Function returns another function*

In [25]:
def create_message():
     print("Welcome David")

def message(x): 
     x()


message(create_message) ## Function returns another function

Welcome David

#### *109.Function reference*

In [26]:
def calculate():
    print("Calculating...")

result = calculate ## function referance
result()

Calculating...

#### *110.Your First Decorators*

In [31]:
def login_required(func):
    
    def Access():
        print("Checking login...")
        print("Access granted...")
        func()

    return Access

@login_required
def dashborad():
    print("Welcome to Dashboard")

dashborad()

Checking login...
Access granted...
Welcome to Dashboard

#### *110.Before and after*

In [35]:
def track_execution(func):

    def inner_func():
        print("Function started")
        func()
        print("Function completed")

    return inner_func

@track_execution
def process_data():
    print("Processing data...")

process_data()

Function started
Processing data...
Function completed

#### *111.Decorator with *args*

In [43]:
def adding_num(func):
    def inner(*args):
        print("Adding numbers...")
        result = func(*args)
        print(f"Result:{result}")
        
    return inner

@adding_num
def add(a,b):
    return a+b

add(10,10)

Adding numbers...
Result:20

#### *112.Authentication decorator*

In [54]:
def login_required(func):
    logged_in = True
    def inner_login(amount):
        if logged_in == True:
            func(amount)

    return inner_login

@login_required
def withdraw_money(amount):
    print(f"your withdraw amount: {amount}")

withdraw_money(200)

your withdraw amount: 200

#### *113.AI API Logger*

In [57]:
def api_logger(func):

    def inner_calling(prompt):
        print("API request started")
        func(prompt)
    return inner_calling


@api_logger
def generate_response(prompt):
    print(f"{prompt}")

generate_response("Prompt: Explain Python decorators")

API request started
Prompt: Explain Python decorators

#### *114.Input validation decorator*

In [14]:
def validate_prompt(func):

    def inner_calling(prompt):
        if prompt == "":
            print(" cannot be empty")
        else:
            func(prompt)

    return inner_calling


@validate_prompt
def ask_ai(prompt):
    print("AI:", prompt)

ask_ai("Explain RAG")

AI: Explain RAG

#### *114.adding decortors*

In [42]:
class demo:
    var = "hi i am from class method"

    def method1(self,a,b):
        return "The Total is" + str(a+b)


    def method2(cls,x,y):
        print("the total is" + str(x*y))
        return cls.var
    
    @staticmethod
    def method3():
      return "hi i am from static method"


obj = demo()
obj.method1(3,3)
obj.method2(4,3)
obj.method3()

the total is12

'hi i am from static method'

In [1]:
def add(a):
    return a + 1

add(2)

3

#### *115.Series 1: Pandas Series*

In [22]:
import pandas as pd

salaries = [18000, 22000, 25000, 30000, 28000]

sd =  pd.Series(salaries)
sd

0    18000
1    22000
2    25000
3    30000
4    28000
dtype: int64

In [23]:
sd.head(3)

0    18000
1    22000
2    25000
dtype: int64

In [24]:
sd.value_counts()

18000    1
22000    1
25000    1
30000    1
28000    1
Name: count, dtype: int64

In [25]:
sd.loc[2]

np.int64(25000)

In [26]:
sd[0] = 20000
sd

0    20000
1    22000
2    25000
3    30000
4    28000
dtype: int64

#### *116.Implicit Index vs Explicit Index*

In [9]:
import pandas as pd

data = {
    "Name": ["Arun", "Bala", "David", "Kumar", "Ravi"],
    "Age": [21, 23, 25, 22, 24],
    "City": ["Chennai", "Madurai", "Salem", "Trichy", "Coimbatore"]
}

df = pd.DataFrame(data,index=[1,2,3,4,5])
print(df)

    Name  Age        City
1   Arun   21     Chennai
2   Bala   23     Madurai
3  David   25       Salem
4  Kumar   22      Trichy
5   Ravi   24  Coimbatore

In [4]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
df.iloc[0]

Name       Arun
Age          21
City    Chennai
Name: 0, dtype: object

In [10]:
df.loc[5]

Name          Ravi
Age             24
City    Coimbatore
Name: 5, dtype: object

In [11]:
df.loc[[2,4]]

    Name  Age     City
2   Bala   23  Madurai
4  Kumar   22   Trichy

In [12]:
df.reset_index(drop=True,inplace=True)
df

    Name  Age        City
0   Arun   21     Chennai
1   Bala   23     Madurai
2  David   25       Salem
3  Kumar   22      Trichy
4   Ravi   24  Coimbatore

#### *117.Reading Data*

In [13]:
import pandas as pd

df = pd.read_csv("students.csv")
df

    Name  Age        City  Marks
0   Arun   21     Chennai     85
1   Bala   23     Madurai     90
2  David   25       Salem     78
3  Kumar   22      Trichy     88
4   Ravi   24  Coimbatore     95

In [14]:
df.head(5)

    Name  Age        City  Marks
0   Arun   21     Chennai     85
1   Bala   23     Madurai     90
2  David   25       Salem     78
3  Kumar   22      Trichy     88
4   Ravi   24  Coimbatore     95

In [17]:
df.shape

(5, 4)

In [18]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   23.000000  87.200000
std     1.581139   6.300794
min    21.000000  78.000000
25%    22.000000  85.000000
50%    23.000000  88.000000
75%    24.000000  90.000000
max    25.000000  95.000000

In [22]:
df.isnull().sum()

Name     0
Age      0
City     0
Marks    0
dtype: int64

#### *117Create the real-world dataset*

In [2]:
import pandas as pd

df = pd.read_csv("employees.csv")
df

   Employee_ID   Name Department  Age  Salary  Experience Performance
0          101   Arun         IT   25   45000           2        Good
1          102   Bala         HR   30   38000           5     Average
2          103  David         IT   28   60000           4   Excellent
3          104  Priya    Finance   32   55000           7        Good
4          105  Kumar      Sales   26   35000           3     Average
5          106  Divya         IT   29   65000           6   Excellent
6          107   Ravi    Finance   35   70000          10        Good
7          108  Meena      Sales   24   32000           1     Average
8          109   John         HR   31   42000           8        Good
9          110  Sneha         IT   27   58000           4   Excellent

In [3]:
df["Name"]

0     Arun
1     Bala
2    David
3    Priya
4    Kumar
5    Divya
6     Ravi
7    Meena
8     John
9    Sneha
Name: Name, dtype: str

In [4]:
df[["Name","Salary"]]

    Name  Salary
0   Arun   45000
1   Bala   38000
2  David   60000
3  Priya   55000
4  Kumar   35000
5  Divya   65000
6   Ravi   70000
7  Meena   32000
8   John   42000
9  Sneha   58000

In [5]:
df.head(5)

   Employee_ID   Name Department  Age  Salary  Experience Performance
0          101   Arun         IT   25   45000           2        Good
1          102   Bala         HR   30   38000           5     Average
2          103  David         IT   28   60000           4   Excellent
3          104  Priya    Finance   32   55000           7        Good
4          105  Kumar      Sales   26   35000           3     Average

In [6]:
df.tail(3)

   Employee_ID   Name Department  Age  Salary  Experience Performance
7          108  Meena      Sales   24   32000           1     Average
8          109   John         HR   31   42000           8        Good
9          110  Sneha         IT   27   58000           4   Excellent

In [7]:
df.iloc[2]

Employee_ID          103
Name               David
Department            IT
Age                   28
Salary             60000
Experience             4
Performance    Excellent
Name: 2, dtype: object

In [8]:
df[df["Department"] == "IT"]

   Employee_ID   Name Department  Age  Salary  Experience Performance
0          101   Arun         IT   25   45000           2        Good
2          103  David         IT   28   60000           4   Excellent
5          106  Divya         IT   29   65000           6   Excellent
9          110  Sneha         IT   27   58000           4   Excellent

In [9]:
df[df["Salary"]>50000]

   Employee_ID   Name Department  Age  Salary  Experience Performance
2          103  David         IT   28   60000           4   Excellent
3          104  Priya    Finance   32   55000           7        Good
5          106  Divya         IT   29   65000           6   Excellent
6          107   Ravi    Finance   35   70000          10        Good
9          110  Sneha         IT   27   58000           4   Excellent

In [10]:
df[df["Experience"]>5]

   Employee_ID   Name Department  Age  Salary  Experience Performance
3          104  Priya    Finance   32   55000           7        Good
5          106  Divya         IT   29   65000           6   Excellent
6          107   Ravi    Finance   35   70000          10        Good
8          109   John         HR   31   42000           8        Good

In [11]:
df[(df["Department"] == "IT") & (df["Salary"] > 55000)]

   Employee_ID   Name Department  Age  Salary  Experience Performance
2          103  David         IT   28   60000           4   Excellent
5          106  Divya         IT   29   65000           6   Excellent
9          110  Sneha         IT   27   58000           4   Excellent

In [12]:
df[df["Age"]<30]

   Employee_ID   Name Department  Age  Salary  Experience Performance
0          101   Arun         IT   25   45000           2        Good
2          103  David         IT   28   60000           4   Excellent
4          105  Kumar      Sales   26   35000           3     Average
5          106  Divya         IT   29   65000           6   Excellent
7          108  Meena      Sales   24   32000           1     Average
9          110  Sneha         IT   27   58000           4   Excellent

In [13]:
df["Annual_Salary"] = df["Salary"]*12
df

,Employee_ID,Name,Department,Age,Salary,Experience,Performance,Annual_Salary
0,101,Arun,IT,25,45000,2,Good,540000
1,102,Bala,HR,30,38000,5,Average,456000
2,103,David,IT,28,60000,4,Excellent,720000
3,104,Priya,Finance,32,55000,7,Good,660000
4,105,Kumar,Sales,26,35000,3,Average,420000
5,106,Divya,IT,29,65000,6,Excellent,780000
6,107,Ravi,Finance,35,70000,10,Good,840000
7,108,Meena,Sales,24,32000,1,Average,384000
8,109,John,HR,31,42000,8,Good,504000
9,110,Sneha,IT,27,58000,4,Excellent,696000

In [14]:
df["Salary"] = df["Salary"]*1.10
df

,Employee_ID,Name,Department,Age,Salary,Experience,Performance,Annual_Salary
0,101,Arun,IT,25,49500.0,2,Good,540000
1,102,Bala,HR,30,41800.0,5,Average,456000
2,103,David,IT,28,66000.0,4,Excellent,720000
3,104,Priya,Finance,32,60500.0,7,Good,660000
4,105,Kumar,Sales,26,38500.0,3,Average,420000
5,106,Divya,IT,29,71500.0,6,Excellent,780000
6,107,Ravi,Finance,35,77000.0,10,Good,840000
7,108,Meena,Sales,24,35200.0,1,Average,384000
8,109,John,HR,31,46200.0,8,Good,504000
9,110,Sneha,IT,27,63800.0,4,Excellent,696000

In [15]:
df["Seniority"] = df["Experience"].apply(
    lambda x:  "senior" if x >=5 else "junior"
)
df

,Employee_ID,Name,Department,Age,Salary,Experience,Performance,Annual_Salary,Seniority
0,101,Arun,IT,25,49500.0,2,Good,540000,junior
1,102,Bala,HR,30,41800.0,5,Average,456000,senior
2,103,David,IT,28,66000.0,4,Excellent,720000,junior
3,104,Priya,Finance,32,60500.0,7,Good,660000,senior
4,105,Kumar,Sales,26,38500.0,3,Average,420000,junior
5,106,Divya,IT,29,71500.0,6,Excellent,780000,senior
6,107,Ravi,Finance,35,77000.0,10,Good,840000,senior
7,108,Meena,Sales,24,35200.0,1,Average,384000,junior
8,109,John,HR,31,46200.0,8,Good,504000,senior
9,110,Sneha,IT,27,63800.0,4,Excellent,696000,junior

In [16]:
df.rename(columns={"Salary":"Monthly_Salar"}, inplace=True)
df

,Employee_ID,Name,Department,Age,Monthly_Salar,Experience,Performance,Annual_Salary,Seniority
0,101,Arun,IT,25,49500.0,2,Good,540000,junior
1,102,Bala,HR,30,41800.0,5,Average,456000,senior
2,103,David,IT,28,66000.0,4,Excellent,720000,junior
3,104,Priya,Finance,32,60500.0,7,Good,660000,senior
4,105,Kumar,Sales,26,38500.0,3,Average,420000,junior
5,106,Divya,IT,29,71500.0,6,Excellent,780000,senior
6,107,Ravi,Finance,35,77000.0,10,Good,840000,senior
7,108,Meena,Sales,24,35200.0,1,Average,384000,junior
8,109,John,HR,31,46200.0,8,Good,504000,senior
9,110,Sneha,IT,27,63800.0,4,Excellent,696000,junior

In [17]:
df["Name"] = df["Name"].str.upper()
df

,Employee_ID,Name,Department,Age,Monthly_Salar,Experience,Performance,Annual_Salary,Seniority
0,101,ARUN,IT,25,49500.0,2,Good,540000,junior
1,102,BALA,HR,30,41800.0,5,Average,456000,senior
2,103,DAVID,IT,28,66000.0,4,Excellent,720000,junior
3,104,PRIYA,Finance,32,60500.0,7,Good,660000,senior
4,105,KUMAR,Sales,26,38500.0,3,Average,420000,junior
5,106,DIVYA,IT,29,71500.0,6,Excellent,780000,senior
6,107,RAVI,Finance,35,77000.0,10,Good,840000,senior
7,108,MEENA,Sales,24,35200.0,1,Average,384000,junior
8,109,JOHN,HR,31,46200.0,8,Good,504000,senior
9,110,SNEHA,IT,27,63800.0,4,Excellent,696000,junior

In [18]:
df.Employee_ID

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Employee_ID, dtype: int64

In [19]:
df[["Employee_ID","Name"]].head()

   Employee_ID   Name
0          101   ARUN
1          102   BALA
2          103  DAVID
3          104  PRIYA
4          105  KUMAR

In [20]:
df["Name"].unique()

<ArrowStringArray>
[ 'ARUN',  'BALA', 'DAVID', 'PRIYA', 'KUMAR', 'DIVYA',  'RAVI', 'MEENA',
  'JOHN', 'SNEHA']
Length: 10, dtype: str

In [21]:
df["Name"].nunique()

10

In [22]:
df["Experience"].value_counts()

Experience
4     2
2     1
5     1
7     1
3     1
6     1
10    1
1     1
8     1
Name: count, dtype: int64

#### *118 .Rename Columns & Delete Columns*

In [23]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Arun", "Bala", "David", "Priya", "Ravi"],
    "Department": ["IT", "HR", "IT", "Finance", "Sales"],
    "Salary": [45000, 38000, 60000, 55000, 35000],
    "Age": [25, 30, 28, 32, 26]
}

df = pd.DataFrame(data)
df

   Emp_ID   Name Department  Salary  Age
0     101   Arun         IT   45000   25
1     102   Bala         HR   38000   30
2     103  David         IT   60000   28
3     104  Priya    Finance   55000   32
4     105   Ravi      Sales   35000   26

In [24]:
df.rename(columns={"Salary":"Monthly_Salary"},inplace=True)
df

   Emp_ID   Name Department  Monthly_Salary  Age
0     101   Arun         IT           45000   25
1     102   Bala         HR           38000   30
2     103  David         IT           60000   28
3     104  Priya    Finance           55000   32
4     105   Ravi      Sales           35000   26

In [25]:
df.rename(columns={"Department":"Team"},inplace=True)
df

   Emp_ID   Name     Team  Monthly_Salary  Age
0     101   Arun       IT           45000   25
1     102   Bala       HR           38000   30
2     103  David       IT           60000   28
3     104  Priya  Finance           55000   32
4     105   Ravi    Sales           35000   26

In [26]:
df.drop(columns="Age", inplace=True)
df

   Emp_ID   Name     Team  Monthly_Salary
0     101   Arun       IT           45000
1     102   Bala       HR           38000
2     103  David       IT           60000
3     104  Priya  Finance           55000
4     105   Ravi    Sales           35000

In [29]:
df.drop(columns="Emp_ID",inplace=True)

In [33]:
df2 = df.copy
df2

<bound method NDFrame.copy of     Name     Team  Monthly_Salary
0   Arun       IT           45000
1   Bala       HR           38000
2  David       IT           60000
3  Priya  Finance           55000
4   Ravi    Sales           35000>

#### *119 .Adding New Columns*

In [37]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Arun", "Bala", "David", "Priya", "Ravi"],
    "Department": ["IT", "HR", "IT", "Finance", "Sales"],
    "Age": [25, 30, 28, 32, 26],
    "Salary": [45000, 38000, 60000, 55000, 35000],
    "Experience": [2, 5, 4, 7, 3]
}

df = pd.DataFrame(data)
df

   Emp_ID   Name Department  Age  Salary  Experience
0     101   Arun         IT   25   45000           2
1     102   Bala         HR   30   38000           5
2     103  David         IT   28   60000           4
3     104  Priya    Finance   32   55000           7
4     105   Ravi      Sales   26   35000           3

In [39]:
df["Annual_Salary"] = df["Salary"]*12
df

   Emp_ID   Name Department  Age  Salary  Experience  Annual_Salary
0     101   Arun         IT   25   45000           2         540000
1     102   Bala         HR   30   38000           5         456000
2     103  David         IT   28   60000           4         720000
3     104  Priya    Finance   32   55000           7         660000
4     105   Ravi      Sales   26   35000           3         420000

In [42]:
df["Salary"] = df["Salary"]*1.10
df

   Emp_ID   Name Department  Age   Salary  Experience  Annual_Salary
0     101   Arun         IT   25  49500.0           2         540000
1     102   Bala         HR   30  41800.0           5         456000
2     103  David         IT   28  66000.0           4         720000
3     104  Priya    Finance   32  60500.0           7         660000
4     105   Ravi      Sales   26  38500.0           3         420000

In [43]:
df["Total_Salary"] = df["Salary"]*1.10
df

,Emp_ID,Name,Department,Age,Salary,Experience,Annual_Salary,Total_Salary
0,101,Arun,IT,25,49500.0,2,540000,54450.0
1,102,Bala,HR,30,41800.0,5,456000,45980.0
2,103,David,IT,28,66000.0,4,720000,72600.0
3,104,Priya,Finance,32,60500.0,7,660000,66550.0
4,105,Ravi,Sales,26,38500.0,3,420000,42350.0

In [45]:
df["Experience_Months"] =  df["Experience"] *  12
df

,Emp_ID,Name,Department,Age,Salary,Experience,Annual_Salary,Total_Salary,Experience_Months
0,101,Arun,IT,25,49500.0,2,540000,54450.0,24
1,102,Bala,HR,30,41800.0,5,456000,45980.0,60
2,103,David,IT,28,66000.0,4,720000,72600.0,48
3,104,Priya,Finance,32,60500.0,7,660000,66550.0,84
4,105,Ravi,Sales,26,38500.0,3,420000,42350.0,36

In [47]:
df["Department_Code"] = "EMP"
df

,Emp_ID,Name,Department,Age,Salary,Experience,Annual_Salary,Total_Salary,Experience_Months,Department_Code
0,101,Arun,IT,25,49500.0,2,540000,54450.0,24,EMP
1,102,Bala,HR,30,41800.0,5,456000,45980.0,60,EMP
2,103,David,IT,28,66000.0,4,720000,72600.0,48,EMP
3,104,Priya,Finance,32,60500.0,7,660000,66550.0,84,EMP
4,105,Ravi,Sales,26,38500.0,3,420000,42350.0,36,EMP

In [49]:
df["Seniority"] = df["Experience"].apply(
    lambda x: "senior" if x >=5 else "junior"
)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Annual_Salary,Total_Salary,Experience_Months,Department_Code,Seniority
0,101,Arun,IT,25,49500.0,2,540000,54450.0,24,EMP,junior
1,102,Bala,HR,30,41800.0,5,456000,45980.0,60,EMP,senior
2,103,David,IT,28,66000.0,4,720000,72600.0,48,EMP,junior
3,104,Priya,Finance,32,60500.0,7,660000,66550.0,84,EMP,senior
4,105,Ravi,Sales,26,38500.0,3,420000,42350.0,36,EMP,junior

In [52]:
df["Salary_Status"] = df["Salary"].apply(
    lambda x:"High Salary" if x >50000 else "Low Salary"
)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Annual_Salary,Total_Salary,Experience_Months,Department_Code,Seniority,Salary_Status
0,101,Arun,IT,25,49500.0,2,540000,54450.0,24,EMP,junior,Low Salary
1,102,Bala,HR,30,41800.0,5,456000,45980.0,60,EMP,senior,Low Salary
2,103,David,IT,28,66000.0,4,720000,72600.0,48,EMP,junior,High Salary
3,104,Priya,Finance,32,60500.0,7,660000,66550.0,84,EMP,senior,High Salary
4,105,Ravi,Sales,26,38500.0,3,420000,42350.0,36,EMP,junior,Low Salary

In [53]:
df["Experience_Level"] = df["Experience"].apply(
    lambda x: "Expert" if x >= 8
    else "Intermediate" if x >= 4
    else "Beginner"
)

df

,Emp_ID,Name,Department,Age,Salary,Experience,Annual_Salary,Total_Salary,Experience_Months,Department_Code,Seniority,Salary_Status,Experience_Level
0,101,Arun,IT,25,49500.0,2,540000,54450.0,24,EMP,junior,Low Salary,Beginner
1,102,Bala,HR,30,41800.0,5,456000,45980.0,60,EMP,senior,Low Salary,Intermediate
2,103,David,IT,28,66000.0,4,720000,72600.0,48,EMP,junior,High Salary,Intermediate
3,104,Priya,Finance,32,60500.0,7,660000,66550.0,84,EMP,senior,High Salary,Intermediate
4,105,Ravi,Sales,26,38500.0,3,420000,42350.0,36,EMP,junior,Low Salary,Beginner

#### *119 .E-commerce Customer & Sales Analysis*

In [ ]:
import pandas as pd

df = pd.read_csv("ecommerce_sales.csv")
df

   Order_ID Customer       City     Product  Quantity  Price Payment_Status
0      1001     Arun    Chennai      Laptop         1  55000           Paid
1      1002    Priya  Bangalore      Mobile         2  20000           Paid
2      1003    David  Hyderabad  Headphones         3   2000        Pending
3      1004    Meena    Chennai      Tablet         1  18000           Paid
4      1005     Ravi     Mumbai    Keyboard         2   1500        Pending
5      1006    Sneha  Bangalore     Monitor         1  12000           Paid
6      1007    Kumar    Chennai      Mobile         1  22000           Paid
7      1008    Divya  Hyderabad      Laptop         1  60000        Pending

In [59]:
df.iloc[0]

Order_ID             1001
Customer             Arun
City              Chennai
Product            Laptop
Quantity                1
Price               55000
Payment_Status       Paid
Name: 0, dtype: object

In [60]:
df.iloc[5]

Order_ID               1006
Customer              Sneha
City              Bangalore
Product             Monitor
Quantity                  1
Price                 12000
Payment_Status         Paid
Name: 5, dtype: object

In [61]:
df.set_index("Order_ID",inplace=True)
df

         Customer       City     Product  Quantity  Price Payment_Status
Order_ID
1001         Arun    Chennai      Laptop         1  55000           Paid
1002        Priya  Bangalore      Mobile         2  20000           Paid
1003        David  Hyderabad  Headphones         3   2000        Pending
1004        Meena    Chennai      Tablet         1  18000           Paid
1005         Ravi     Mumbai    Keyboard         2   1500        Pending
1006        Sneha  Bangalore     Monitor         1  12000           Paid
1007        Kumar    Chennai      Mobile         1  22000           Paid
1008        Divya  Hyderabad      Laptop         1  60000        Pending

In [64]:
df.reset_index(drop=True,inplace=True)

In [69]:
import pandas as pd

df = pd.read_csv("ecommerce_sales.csv")

df

   Order_ID Customer       City     Product  Quantity  Price Payment_Status
0      1001     Arun    Chennai      Laptop         1  55000           Paid
1      1002    Priya  Bangalore      Mobile         2  20000           Paid
2      1003    David  Hyderabad  Headphones         3   2000        Pending
3      1004    Meena    Chennai      Tablet         1  18000           Paid
4      1005     Ravi     Mumbai    Keyboard         2   1500        Pending
5      1006    Sneha  Bangalore     Monitor         1  12000           Paid
6      1007    Kumar    Chennai      Mobile         1  22000           Paid
7      1008    Divya  Hyderabad      Laptop         1  60000        Pending

In [71]:
df.loc[8] = [1009, "Karthik", "Coimbatore", "Mouse", 2, 800, "Paid"]

df

   Order_ID Customer        City     Product  Quantity  Price Payment_Status
0      1001     Arun     Chennai      Laptop         1  55000           Paid
1      1002    Priya   Bangalore      Mobile         2  20000           Paid
2      1003    David   Hyderabad  Headphones         3   2000        Pending
3      1004    Meena     Chennai      Tablet         1  18000           Paid
4      1005     Ravi      Mumbai    Keyboard         2   1500        Pending
5      1006    Sneha   Bangalore     Monitor         1  12000           Paid
6      1007    Kumar     Chennai      Mobile         1  22000           Paid
7      1008    Divya   Hyderabad      Laptop         1  60000        Pending
8      1009  Karthik  Coimbatore       Mouse         2    800           Paid

In [ ]:
new_row = [1009, "Karthik", "Coimbatore", "Mouse", 2, 800, "Paid"]

In [74]:
new_row = [1009, "Karthik", "Coimbatore", "Mouse", 2, 800, "Paid"]

df.loc[len(df.index)] = new_row

df

   Order_ID Customer        City     Product  Quantity  Price Payment_Status
0      1001     Arun     Chennai      Laptop         1  55000           Paid
1      1002    Priya   Bangalore      Mobile         2  20000           Paid
2      1003    David   Hyderabad  Headphones         3   2000        Pending
3      1004    Meena     Chennai      Tablet         1  18000           Paid
4      1005     Ravi      Mumbai    Keyboard         2   1500        Pending
5      1006    Sneha   Bangalore     Monitor         1  12000           Paid
6      1007    Kumar     Chennai      Mobile         1  22000           Paid
7      1008    Divya   Hyderabad      Laptop         1  60000        Pending
8      1009  Karthik  Coimbatore       Mouse         2    800           Paid
9      1009  Karthik  Coimbatore       Mouse         2    800           Paid

In [79]:
df.iloc[10] = [1009, "Karthik", "Coimbatore", "Mouse", 2, 800, "unPaid"]
df

    Order_ID Customer        City     Product  Quantity  Price Payment_Status
0       1001     Arun     Chennai      Laptop         1  55000           Paid
1       1002    Priya   Bangalore      Mobile         2  20000           Paid
2       1003    David   Hyderabad  Headphones         3   2000        Pending
3       1004    Meena     Chennai      Tablet         1  18000           Paid
4       1005     Ravi      Mumbai    Keyboard         2   1500        Pending
5       1006    Sneha   Bangalore     Monitor         1  12000           Paid
6       1007    Kumar     Chennai      Mobile         1  22000           Paid
7       1008    Divya   Hyderabad      Laptop         1  60000        Pending
8       1009  Karthik  Coimbatore       Mouse         2    800           Paid
9       1009  Karthik  Coimbatore       Mouse         2    800           Paid
10      1009  Karthik  Coimbatore       Mouse         2    800         unPaid

In [82]:
df.drop(5,axis=0)

    Order_ID Customer        City     Product  Quantity  Price Payment_Status
0       1001     Arun     Chennai      Laptop         1  55000           Paid
1       1002    Priya   Bangalore      Mobile         2  20000           Paid
2       1003    David   Hyderabad  Headphones         3   2000        Pending
3       1004    Meena     Chennai      Tablet         1  18000           Paid
4       1005     Ravi      Mumbai    Keyboard         2   1500        Pending
6       1007    Kumar     Chennai      Mobile         1  22000           Paid
7       1008    Divya   Hyderabad      Laptop         1  60000        Pending
8       1009  Karthik  Coimbatore       Mouse         2    800           Paid
9       1009  Karthik  Coimbatore       Mouse         2    800           Paid
10      1009  Karthik  Coimbatore       Mouse         2    800         unPaid

In [84]:
df.drop("Payment_Status",axis=1)

    Order_ID Customer        City     Product  Quantity  Price
0       1001     Arun     Chennai      Laptop         1  55000
1       1002    Priya   Bangalore      Mobile         2  20000
2       1003    David   Hyderabad  Headphones         3   2000
3       1004    Meena     Chennai      Tablet         1  18000
4       1005     Ravi      Mumbai    Keyboard         2   1500
5       1006    Sneha   Bangalore     Monitor         1  12000
6       1007    Kumar     Chennai      Mobile         1  22000
7       1008    Divya   Hyderabad      Laptop         1  60000
8       1009  Karthik  Coimbatore       Mouse         2    800
9       1009  Karthik  Coimbatore       Mouse         2    800
10      1009  Karthik  Coimbatore       Mouse         2    800

In [87]:
df.drop(list(range(2,5)),axis=0)

    Order_ID Customer        City  Product  Quantity  Price Payment_Status
0       1001     Arun     Chennai   Laptop         1  55000           Paid
1       1002    Priya   Bangalore   Mobile         2  20000           Paid
5       1006    Sneha   Bangalore  Monitor         1  12000           Paid
6       1007    Kumar     Chennai   Mobile         1  22000           Paid
7       1008    Divya   Hyderabad   Laptop         1  60000        Pending
8       1009  Karthik  Coimbatore    Mouse         2    800           Paid
9       1009  Karthik  Coimbatore    Mouse         2    800           Paid
10      1009  Karthik  Coimbatore    Mouse         2    800         unPaid

#### *120.Handling Duplicate Data*

In [88]:
import pandas as pd

data = {
    "Order_ID": [1001, 1002, 1003, 1002, 1004, 1005, 1003, 1006, 1007, 1007],
    "Customer": ["Arun", "Priya", "David", "Priya", "Meena",
                 "Ravi", "David", "Sneha", "Kumar", "Kumar"],
    "Product": ["Laptop", "Mobile", "Headphones", "Mobile", "Tablet",
                "Keyboard", "Headphones", "Monitor", "Mouse", "Mouse"],
    "Price": [55000, 20000, 2000, 20000, 18000, 1500, 2000, 12000, 800, 800],
    "Payment_Status": ["Paid", "Paid", "Pending", "Paid", "Paid",
                       "Pending", "Pending", "Paid", "Paid", "Paid"]
}

df = pd.DataFrame(data)
df

   Order_ID Customer     Product  Price Payment_Status
0      1001     Arun      Laptop  55000           Paid
1      1002    Priya      Mobile  20000           Paid
2      1003    David  Headphones   2000        Pending
3      1002    Priya      Mobile  20000           Paid
4      1004    Meena      Tablet  18000           Paid
5      1005     Ravi    Keyboard   1500        Pending
6      1003    David  Headphones   2000        Pending
7      1006    Sneha     Monitor  12000           Paid
8      1007    Kumar       Mouse    800           Paid
9      1007    Kumar       Mouse    800           Paid

In [91]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9     True
dtype: bool

In [92]:
df.duplicated().value_counts()

False    7
True     3
Name: count, dtype: int64

In [93]:
df.duplicated().sum()

np.int64(3)

In [97]:
df_clean  = df.drop_duplicates(inplace=True)
df_clean

In [98]:
df

   Order_ID Customer     Product  Price Payment_Status
0      1001     Arun      Laptop  55000           Paid
1      1002    Priya      Mobile  20000           Paid
2      1003    David  Headphones   2000        Pending
4      1004    Meena      Tablet  18000           Paid
5      1005     Ravi    Keyboard   1500        Pending
7      1006    Sneha     Monitor  12000           Paid
8      1007    Kumar       Mouse    800           Paid

In [101]:
import pandas as pd

data = {
    "Order_ID": [1001, 1002, 1003, 1002, 1004, 1005, 1003, 1006, 1007, 1007],
    "Customer": ["Arun", "Priya", "David", "Priya", "Meena",
                 "Ravi", "David", "Sneha", "Kumar", "Kumar"],
    "Product": ["Laptop", "Mobile", "Headphones", "Mobile", "Tablet",
                "Keyboard", "Headphones", "Monitor", "Mouse", "Mouse"],
    "Price": [55000, 20000, 2000, 20000, 18000, 1500, 2000, 12000, 800, 800],
    "Payment_Status": ["Paid", "Paid", "Pending", "Paid", "Paid",
                       "Pending", "Pending", "Paid", "Paid", "Paid"]
}

df1 = pd.DataFrame(data)
df1

   Order_ID Customer     Product  Price Payment_Status
0      1001     Arun      Laptop  55000           Paid
1      1002    Priya      Mobile  20000           Paid
2      1003    David  Headphones   2000        Pending
3      1002    Priya      Mobile  20000           Paid
4      1004    Meena      Tablet  18000           Paid
5      1005     Ravi    Keyboard   1500        Pending
6      1003    David  Headphones   2000        Pending
7      1006    Sneha     Monitor  12000           Paid
8      1007    Kumar       Mouse    800           Paid
9      1007    Kumar       Mouse    800           Paid

In [ ]:
df1[df1.duplicated(subset=["Customer","Order_ID"])]  # Excludes the first occurrence

   Order_ID Customer     Product  Price Payment_Status
3      1002    Priya      Mobile  20000           Paid
6      1003    David  Headphones   2000        Pending
9      1007    Kumar       Mouse    800           Paid

In [107]:
df1[df1.duplicated(subset=["Order_ID"], keep=False)]

   Order_ID Customer     Product  Price Payment_Status
1      1002    Priya      Mobile  20000           Paid
2      1003    David  Headphones   2000        Pending
3      1002    Priya      Mobile  20000           Paid
6      1003    David  Headphones   2000        Pending
8      1007    Kumar       Mouse    800           Paid
9      1007    Kumar       Mouse    800           Paid

In [112]:
import pandas as pd

data = {
    'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
    'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
    'C': ['small', 'large', 'large', 'small', 'small', 'small', 'large', 'small'],
    'D': [1, 2, 3, 3, 4, 5, 6, 7]
}

df1 = pd.DataFrame(data)

df1

     A      B      C  D
0  foo    one  small  1
1  bar    one  large  2
2  foo    two  large  3
3  bar  three  small  3
4  foo    two  small  4
5  bar    two  small  5
6  foo    one  large  6
7  foo  three  small  7

In [113]:
df1.drop_duplicates(subset=['A','C'])

     A      B      C  D
0  foo    one  small  1
1  bar    one  large  2
2  foo    two  large  3
3  bar  three  small  3

In [114]:
df1.drop_duplicates(subset=['A','C'])

     A      B      C  D
0  foo    one  small  1
1  bar    one  large  2
2  foo    two  large  3
3  bar  three  small  3

In [124]:
users = pd.DataFrame({"userid":[1,2,3],"name":["sharadh","shahid","Khusalali"]})
users

   userid       name
0       1    sharadh
1       2     shahid
2       3  Khusalali

In [125]:
mags = pd.DataFrame({"userid":[1,1,2,4], "msg":["hmm","acha","theek hai","nice"]})
mags

   userid        msg
0       1        hmm
1       1       acha
2       2  theek hai
3       4       nice

In [129]:
df3  = pd.concat([users,mags],ignore_index=True)
df3

   userid       name        msg
0       1    sharadh        NaN
1       2     shahid        NaN
2       3  Khusalali        NaN
3       1        NaN        hmm
4       1        NaN       acha
5       2        NaN  theek hai
6       4        NaN       nice

#### *121.Pandas Merge*

In [133]:
import pandas as pd

employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Arun", "Bala", "David", "Priya", "Ravi"],
    "Dept_ID": [1, 2, 1, 3, 2]
})
employees

   Emp_ID   Name  Dept_ID
0     101   Arun        1
1     102   Bala        2
2     103  David        1
3     104  Priya        3
4     105   Ravi        2

In [135]:
departments = pd.DataFrame({
    "Dept_ID": [1, 2, 3, 4],
    "Department": ["IT", "HR", "Finance", "Sales"]
})
departments

   Dept_ID Department
0        1         IT
1        2         HR
2        3    Finance
3        4      Sales

In [132]:
df4 = pd.concat([employees,departments])
df4

   Emp_ID   Name  Dept_ID Department
0   101.0   Arun        1        NaN
1   102.0   Bala        2        NaN
2   103.0  David        1        NaN
3   104.0  Priya        3        NaN
4   105.0   Ravi        2        NaN
0     NaN    NaN        1         IT
1     NaN    NaN        2         HR
2     NaN    NaN        3    Finance
3     NaN    NaN        4      Sales

In [138]:
employees.merge(departments, on="Dept_ID",how="inner")

   Emp_ID   Name  Dept_ID Department
0     101   Arun        1         IT
1     102   Bala        2         HR
2     103  David        1         IT
3     104  Priya        3    Finance
4     105   Ravi        2         HR

In [139]:
employees.merge(departments, on="Dept_ID", how="left")

   Emp_ID   Name  Dept_ID Department
0     101   Arun        1         IT
1     102   Bala        2         HR
2     103  David        1         IT
3     104  Priya        3    Finance
4     105   Ravi        2         HR

In [141]:
employees.merge(departments, how="right")

   Emp_ID   Name  Dept_ID Department
0   101.0   Arun        1         IT
1   103.0  David        1         IT
2   102.0   Bala        2         HR
3   105.0   Ravi        2         HR
4   104.0  Priya        3    Finance
5     NaN    NaN        4      Sales

In [142]:
employees.merge(departments, how="outer")

   Emp_ID   Name  Dept_ID Department
0   101.0   Arun        1         IT
1   103.0  David        1         IT
2   102.0   Bala        2         HR
3   105.0   Ravi        2         HR
4   104.0  Priya        3    Finance
5     NaN    NaN        4      Sales